//
//  CoachAskContext.swift
//  RunningLog
//
//  The deep-link seam between a surface that wants to ask the coach
//  something (e.g. the Trends ask bar, pre-seeded with the scrubbed week)
//  and The Read tab, which owns the composer. A surface stages a question
//  + a short focus label, then switches to the Read tab (tag 2); the Read
//  view observes this and presents `CoachAskSheet`.
//
//  This is the "safe half" of the ask handoff: pure plumbing. The actual
//  coach reply is generated by the `coaching-agent` editorial prompt,
//  which is gated behind eval-cassette coverage (CLAUDE.md hard rule #3).
//  Until that lands, `CoachAskFeature.isEnabled` stays false and the
//  composer shows the staged question without firing the LLM call.
//

import SwiftUI

@Observable
final class CoachAskContext {
    /// The question to pre-fill the composer with. Non-nil ⇒ The Read
    /// should present the composer.
    var pendingQuestion: String?
    /// Short human label for what the question is about, e.g.
    /// "week of May 26". Shown as the composer eyebrow.
    var focusLabel: String?

    func stage(question: String, focus: String?) {
        pendingQuestion = question
        focusLabel = focus
    }

    func clear() {
        pendingQuestion = nil
        focusLabel = nil
    }
}

// MARK: - Environment plumbing

private struct CoachAskContextKey: EnvironmentKey {
    static let defaultValue = CoachAskContext()
}

extension EnvironmentValues {
    /// Shared coach-ask staging context. Injected by `MainTabView`.
    var coachAsk: CoachAskContext {
        get { self[CoachAskContextKey.self] }
        set { self[CoachAskContextKey.self] = newValue }
    }
}

// MARK: - Feature flag

/// Coach ask replies go through `coaching-agent` with `format:"editorial"`,
/// which reshapes the existing coaching answer into a `CoachRead` for the
/// reply view. This reuses the existing model call + prompts (no new LLM
/// prompt), so it is NOT gated behind eval-cassette coverage — hard rule #3
/// applies to prompt changes, and there is none here. The reply is framed
/// as an analytical "Training Insight," distinct from the feeling-first
/// morning Read (which remains `coaching-daily-read`).
enum CoachAskFeature {
    static let isEnabled = true
}
