//
//  CoachAskSheet.swift
//  RunningLog
//
//  The composer presented on The Read when another surface stages a
//  question via `CoachAskContext` (e.g. the Trends ask bar pre-seeding the
//  scrubbed week). Pre-fills + lets the athlete edit the question.
//
//  The actual reply is generated by the `coaching-agent` editorial prompt,
//  which is gated behind eval-cassette coverage (hard rule #3). While
//  `CoachAskFeature.isEnabled` is false the composer stages the question
//  but does not fire the LLM call. When enabled, it reuses the existing
//  `DailyReadService.ask(_:)` path and renders the returned `CoachRead`.
//

import SwiftUI

struct CoachAskSheet: View {
    let focus: String?

    @Environment(\.dismiss) private var dismiss
    @State private var text: String
    @State private var phase: Phase = .compose

    enum Phase: Equatable {
        case compose
        case loading
        case reply(CoachRead)
        case failed(String)
    }

    init(question: String, focus: String?) {
        self.focus = focus
        _text = State(initialValue: question)
    }

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: 18) {
                    Text(focus.map { "ASK THE COACH · \($0.uppercased())" } ?? "ASK THE COACH")
                        .font(.dripEyebrow(10))
                        .tracking(1.3)
                        .foregroundStyle(Color.drip.coral)

                    composer

                    switch phase {
                    case .compose:
                        EmptyView()
                    case .loading:
                        loadingView
                    case .reply(let read):
                        replyView(read)
                    case .failed(let msg):
                        Text(msg)
                            .font(.dripBody(14))
                            .foregroundStyle(Color.drip.tired)
                    }
                }
                .padding(20)
                .frame(maxWidth: .infinity, alignment: .leading)
            }
            .background(Color.drip.background.ignoresSafeArea())
            .toolbar {
                ToolbarItem(placement: .topBarLeading) {
                    Button("Close") { dismiss() }
                        .foregroundStyle(Color.drip.textSecondary)
                }
            }
        }
    }

    // MARK: - Composer

    private var composer: some View {
        VStack(alignment: .leading, spacing: 12) {
            TextEditor(text: $text)
                .font(.dripBody(16))
                .frame(minHeight: 96)
                .scrollContentBackground(.hidden)
                .padding(10)
                .background(Color.drip.cardBackground)
                .clipShape(RoundedRectangle(cornerRadius: 8))
                .overlay(
                    RoundedRectangle(cornerRadius: 8)
                        .stroke(Color.drip.divider, lineWidth: 1)
                )

            if CoachAskFeature.isEnabled {
                Button {
                    Task { await ask() }
                } label: {
                    Text("Ask")
                        .font(.dripLabel(15))
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, 14)
                        .background(Color.drip.coral)
                        .foregroundStyle(.white)
                        .clipShape(RoundedRectangle(cornerRadius: 10))
                }
                .buttonStyle(.plain)
                .disabled(
                    text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
                        || phase == .loading
                )
            } else {
                Text("Coach replies aren't live yet — this is the question we'll ask once the editorial Read ships.")
                    .font(.dripBody(13).italic())
                    .foregroundStyle(Color.drip.textSecondary)
                    .fixedSize(horizontal: false, vertical: true)
            }
        }
    }

    private var loadingView: some View {
        HStack(spacing: 10) {
            ProgressView().tint(Color.drip.coral)
            Text("Reading…")
                .font(.dripBody(14))
                .foregroundStyle(Color.drip.textSecondary)
        }
    }

    private func replyView(_ read: CoachRead) -> some View {
        VStack(alignment: .leading, spacing: 10) {
            EditorialRule()
            Text(read.headline)
                .font(.dripDisplay(22))
                .foregroundStyle(Color.drip.textPrimary)
            Text(plainText(read))
                .font(.dripBody(16))
                .foregroundStyle(Color.drip.textPrimary)
                .lineSpacing(4)
            Text("\(read.confidence.level.rawValue) · \(read.confidence.sub)")
                .font(.dripEyebrow(10))
                .tracking(1.0)
                .foregroundStyle(Color.drip.textSecondary)
        }
    }

    // MARK: - Actions

    private func ask() async {
        phase = .loading
        do {
            let read = try await DailyReadService.shared.ask(text)
            phase = .reply(read)
        } catch {
            phase = .failed("Couldn't reach the coach just now. Try again in a moment.")
        }
    }

    /// Flatten the reply to its prose (citations rendered inline are a
    /// future refinement; this strips them to plain text for now).
    private func plainText(_ read: CoachRead) -> String {
        read.paragraph
            .compactMap { if case .text(let s) = $0 { return s } else { return nil } }
            .joined()
    }
}
