/**
 * Athlete Signature — engine types (addendum §4).
 *
 * The miner is PURE MATH: deterministic, testable, cheap, explainable
 * (addendum principle #5). It takes an athlete's day-level timeline and emits
 * validated observations with their statistics attached. An LLM phrases them
 * later (S2); the miner NEVER invents a pattern and NEVER writes prose.
 *
 * Shape of the pipeline (all pure functions, no I/O):
 *
 *   AthleteDay[]  ──grammar──►  Hypothesis[]  ──stats──►  Candidate[]
 *                                                  │
 *                                              gates + scoring
 *                                                  │
 *                                            SignatureObservation[]
 *
 * The edge function (mine-athlete-signature, built in a later pass) is the
 * only thing that does I/O: it loads the timeline from the existing tables,
 * calls mineSignature(), and upserts the results under the service role.
 */

// ── Closed vocabularies (mirror the DB CHECK constraints in the migration) ────

/** Display grouping + the niggle gate (§7). Must match the DB category CHECK. */
export type Category =
  | "performance"
  | "recovery"
  | "load_response"
  | "mood"
  | "niggle_assoc"
  | "schedule"
  | "environment";

/** Confidence ladder (§ principle 3). `low` never leaves the miner. */
export type Confidence = "low" | "medium" | "high";

/**
 * Heat-stress band (addendum §4.3), derived per-workout from dew point.
 * Used both as an antecedent and, in production, as a baseline adjuster so a
 * July tempo isn't judged against a January one.
 */
export type HeatBand = "comfortable" | "moderate" | "humid" | "oppressive";

/** Feeling chip (base-spec S3). A cleaner outcome than pace-vs-zone alone. */
export type FeelChip = "nailed_it" | "on_track" | "struggled";

// ── The substrate: one row per calendar day of the athlete's history ──────────

/**
 * A single day in the athlete's timeline. Every field is already collected by
 * the app (addendum §3) — the edge function derives these from training_logs,
 * running_workout_laps, athlete_state satellites, body_mentions, weather_actual,
 * and (once F1 ships) feel chips. The miner needs no new capture.
 *
 * Fields are nullable because coverage varies by window and by athlete: a day
 * before signup has paces but no mood; an easy run has no work-segment pace.
 * The grammar's `present()` predicates decide, per outcome, whether a day
 * carries a usable measurement — nulls are simply skipped, never imputed.
 */
export interface AthleteDay {
  /** ISO calendar date, `YYYY-MM-DD`. The timeline is one entry per date. */
  date: string;

  /** The training_logs.id for the run on this day, for evidence example ids. */
  logId: string | null;

  // — raw shape of the day —
  ran: boolean;
  restDay: boolean;
  crossTrain: boolean; // bike / swim — allowed as an antecedent, never a fitness outcome (§3)
  distanceMiles: number | null;
  durationMinutes: number | null;
  workoutType: string | null;
  isQuality: boolean;
  isLongRun: boolean;

  /** Morning vs evening start — the pilot's cleanest contrast. */
  startPeriod: "am" | "pm" | null;
  /** Per-workout heat band from dew point (§4.3). */
  heatBand: HeatBand | null;

  // — precomputed weekly flags (cheap to compute upstream; read as booleans here) —
  /** Weekly intensity-minutes jumped ≥ 15% vs the prior week. */
  intensityJumpWeek: boolean;
  /** Down week — volume < 80% of the trailing 4-week average. */
  downWeek: boolean;

  // — outcome measurements (athlete-relative comparison happens in stats.ts) —
  /** Mean WORK-SEGMENT pace (m/s) for a quality session. Segment rule (§4.1):
   *  never a whole-activity average — that's mostly jog recovery. */
  workSegmentPaceMps: number | null;
  /** Mean work-segment HR (bpm) at work pace. */
  workSegmentHr: number | null;
  /** Cardiac-cost proxy on matched-band easy runs: effort per km. */
  easyEffortPerKm: number | null;
  /** Long-run fade: last-3mi pace minus first-3mi pace (s/mi; + = faded). */
  longRunFadeSecPerMile: number | null;

  moodLabel: string | null;
  feelChip: FeelChip | null;
  /** Did the athlete mention a niggle on this day (verbatim body-part mention)? */
  niggleMentioned: boolean;
  niggleBodyArea: string | null;
  /** Scheduled-vs-actual compliance for the day, 0..1. */
  compliance: number | null;

  /**
   * Derived internal tag set by grammar.tagDerivedAntecedents — true when this
   * quality day directly follows another quality day. Kept on the row so the
   * b2b_quality antecedent predicate stays a pure function of a single day.
   * Not persisted; recomputed each mining run.
   */
  _b2bQuality?: boolean;
}

// ── Grammar (§4.1) — an OPEN space, generated by code, never enumerated ────────

export interface GrammarContext {
  /** All present outcome days already indexed by date, filled by the miner. */
  byDate: Map<string, AthleteDay>;
}

/**
 * An antecedent is a condition over the timeline. Two flavors:
 *  - EVENT antecedent (rest day, long run, intensity jump…): marks trigger
 *    days; outcomes are measured at a lag afterward (case vs. control).
 *  - CONDITION contrast (AM vs PM, oppressive vs comfortable heat…): partitions
 *    same-day outcome measurements into two arms and compares them directly.
 * New antecedents extend the grammar by adding one object here — no redesign.
 */
export interface Antecedent {
  key: string; // machine token, e.g. "rest_day", "start_pm"
  label: string; // short human phrase for later phrasing scaffolds
  category: Category;
  /** Condition contrasts compare arm-A vs arm-B on the SAME day only. */
  sameDayOnly?: boolean;
  /** Is this day a trigger (event) / arm-A (contrast) day? */
  exposed: (day: AthleteDay) => boolean;
  /** Explicit baseline arm for a contrast. If omitted, baseline = "not exposed". */
  baseline?: (day: AthleteDay) => boolean;
}

/** A lag maps a trigger day to the outcome day(s), as a calendar-day offset range. */
export interface Lag {
  key: string; // "same_day", "+2d", "4-7d", …
  label: string;
  /** Inclusive offset range in days relative to the trigger day. */
  offset: [number, number];
}

/** An outcome is a measurement, compared against the ATHLETE'S OWN baseline. */
export interface Outcome {
  key: string; // "work_pace", "easy_effort", "mood", "niggle", …
  label: string;
  kind: "continuous" | "rate";
  category: Category;
  /** Does this day carry a usable measurement of this outcome? */
  present: (day: AthleteDay) => boolean;
  /** Continuous reading (kind === "continuous"). */
  value?: (day: AthleteDay) => number | null;
  /** Did the tracked event occur (kind === "rate")? */
  event?: (day: AthleteDay) => boolean;
}

/** One point in the cross-product the miner will test. */
export interface Hypothesis {
  antecedent: Antecedent;
  lag: Lag;
  outcome: Outcome;
}

// ── Output ────────────────────────────────────────────────────────────────────

/** The statistical case, serialized to the `evidence` JSONB column. */
export interface Evidence {
  n: number; // exposed support
  baseline_n: number;
  /** Athlete's own baseline: mean (continuous) or rate (0..1). */
  base_rate: number;
  /** Conditional value under the antecedent: mean or rate. */
  conditional_rate: number;
  /** personal-SD units (continuous) or rate difference (rate). */
  effect: number;
  effect_unit: "personal_sd" | "rate_diff";
  window_start: string;
  window_end: string;
  example_log_ids: string[];
  last_instance_at: string;
  split_half: {
    first: { effect: number; n: number };
    second: { effect: number; n: number };
  };
  antecedent: string;
  outcome: string;
  lag: string;
}

/**
 * A validated observation, ready to upsert into
 * athlete_signature_observations. The miner emits `candidate`; the weekly
 * lifecycle promotes to `active` only after a re-test on new data (§4.2 #4).
 * `statement` is null here — phrasing is an LLM step (S2), gated by evals.
 */
export interface SignatureObservation {
  patternKey: string; // e.g. "rest_day->work_pace@+2d"
  category: Category;
  statement: null;
  evidence: Evidence;
  confidence: Exclude<Confidence, "low">; // low is dropped before this point
  status: "candidate";
}

// ── Gate configuration (§4.2). Defaults reflect the pilot's proven gates. ──────

export interface GateConfig {
  /** Min history span before an athlete is mined at all (§4.2). */
  minHistoryDays: number;
  /** Support floor: ≥ this many exposed AND baseline observations. */
  minSupport: number;
  /** Effect floor for continuous outcomes, in personal SDs. */
  minEffectSd: number;
  /** Effect floor for rate outcomes, as an absolute rate difference. */
  minEffectRate: number;
  /** Per-half min support for the split-half confirmation. */
  minHalfSupport: number;
  /** Per-half effect floor as a fraction of the main floor. */
  halfEffectFraction: number;
  /** Max `active`/`candidate` observations kept per athlete. */
  cap: number;
}

export const DEFAULT_GATES: GateConfig = {
  minHistoryDays: 84, // 12 weeks
  minSupport: 6,
  minEffectSd: 0.5,
  minEffectRate: 0.2,
  minHalfSupport: 3,
  halfEffectFraction: 0.6,
  cap: 12,
};
