-- ============================================================================
-- Weekly Coaching Report Cron Schedule
--
-- Runs every Monday at 6:00 AM UTC to generate weekly coaching reports
-- for all users with active training plans.
--
-- Requires pg_cron and pg_net extensions to be enabled.
-- Run manually if not yet enabled:
--
--   SELECT cron.schedule(
--     'weekly-coaching-reports',
--     '0 6 * * 1',
--     $$
--     SELECT net.http_post(
--       url := current_setting('app.settings.supabase_url') || '/functions/v1/weekly-coaching-report',
--       headers := jsonb_build_object(
--         'Content-Type', 'application/json',
--         'Authorization', 'Bearer ' || current_setting('app.settings.service_role_key')
--       ),
--       body := '{"batch": true}'::jsonb
--     );
--     $$
--   );
--
-- To check schedule:   SELECT * FROM cron.job;
-- To remove schedule:  SELECT cron.unschedule('weekly-coaching-reports');
-- ============================================================================
