-- ============================================================================
-- Athlete-side adaptive plan UX — schema additions
--
-- Adds the columns the new athlete plan experience needs to land safely.
-- All columns are nullable so this migration is backwards-compatible: the
-- existing `subscribe-to-plan` + reconciliation paths keep working, and the
-- new UI treats missing values as "not yet backfilled."
--
-- See docs/athlete-plan-ux.md §4 for the full rationale.
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- scheduled_workouts: per-day coach rationale
--
-- The athlete's plan view surfaces a 1-line subtitle under each day
-- explaining WHY this workout on this day; the "Why?" drawer expands into a
-- structured triple (why today, why this workout, why this pace).
--
-- Populated by `generate-day-rationale` (Phase 4) at plan materialization
-- time and re-generated whenever a week is reshaped. Nullable because all
-- existing rows pre-date this feature; the UI has a graceful fallback.
-- ---------------------------------------------------------------------------

ALTER TABLE scheduled_workouts
    ADD COLUMN IF NOT EXISTS rationale_short TEXT,
    ADD COLUMN IF NOT EXISTS rationale_full JSONB;

COMMENT ON COLUMN scheduled_workouts.rationale_short IS
    'One-line coach rationale shown as subtitle on the athlete''s week view. '
    'Generated by generate-day-rationale. Null = not yet backfilled.';

COMMENT ON COLUMN scheduled_workouts.rationale_full IS
    'Structured rationale: { why_today, why_this_workout, why_this_pace }. '
    'Surfaced in the "Why?" drawer. Null = not yet backfilled.';


-- ---------------------------------------------------------------------------
-- plan_adjustments: three-tier customization model
--
-- The athlete can mutate their own plan (shift a day, reshape a week, skip a
-- quality). Every mutation writes a plan_adjustments row. The tier drives
-- whether it flags to the coach:
--   green  — routine, logged, not flagged (e.g. shift quality ±2 days)
--   yellow — allowed, visible to coach on dashboard (e.g. skip a quality)
--   red    — blocked, must go through coach chat (e.g. edit race date)
--
-- reason_code is the picker bucket; reason_text is the free-text when
-- "something else" is chosen.
-- ---------------------------------------------------------------------------

ALTER TABLE plan_adjustments
    ADD COLUMN IF NOT EXISTS tier TEXT
        CHECK (tier IS NULL OR tier IN ('green', 'yellow', 'red')),
    ADD COLUMN IF NOT EXISTS reason_code TEXT,
    ADD COLUMN IF NOT EXISTS reason_text TEXT,
    ADD COLUMN IF NOT EXISTS week_number INTEGER;

COMMENT ON COLUMN plan_adjustments.tier IS
    'Athlete-action severity: green (routine), yellow (flagged to coach), '
    'red (blocked). Null = legacy row from before this column existed.';

COMMENT ON COLUMN plan_adjustments.reason_code IS
    'Bucket for the change: travel, flat_week, extra_rest_day, extra_day, other.';

COMMENT ON COLUMN plan_adjustments.reason_text IS
    'Free-text when athlete picks "something else" or adds detail.';

COMMENT ON COLUMN plan_adjustments.week_number IS
    'Which plan-week this adjustment affects. Useful for scoping weekly '
    'reshapes and building the coach''s "adjustments this week" view.';


-- ---------------------------------------------------------------------------
-- plan_adjustments.action_type: extend the CHECK to include athlete-driven
-- actions. Existing values (reprice_future_paces, reduce_volume, etc.) were
-- coach/system initiated; we're adding the two new athlete verbs.
-- ---------------------------------------------------------------------------

ALTER TABLE plan_adjustments
    DROP CONSTRAINT IF EXISTS plan_adjustments_action_type_check;

ALTER TABLE plan_adjustments
    ADD CONSTRAINT plan_adjustments_action_type_check
        CHECK (action_type IN (
            'reprice_future_paces',
            'reduce_volume',
            'cap_volume',
            'propose_swap',
            'update_fitness',
            'pause_quality',
            'shift_day',           -- athlete shifts a single day within a week
            'reshape_week'         -- athlete re-plans a week within coach constraints
        ));


-- ---------------------------------------------------------------------------
-- Index to support "this athlete's recent yellow-tier adjustments" — the
-- coach's dashboard query. Partial index keeps it small (most rows are
-- either null tier or green).
-- ---------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_plan_adjustments_tier_applied
    ON plan_adjustments(user_id, applied_at DESC)
    WHERE tier IS NOT NULL AND tier <> 'green';


COMMIT;
