-- ============================================================================
-- Reconcile ledger drift: re-apply the athlete-plan-UX columns that
-- 20260424100000_athlete_plan_ux.sql was supposed to add.
--
-- WHY THIS EXISTS
-- ---------------
-- `20260424100000` is recorded in supabase_migrations.schema_migrations as
-- APPLIED, but its DDL never actually ran against this project (verified
-- 2026-07-03 against prod aqdijapxmjqaetursrde): plan_adjustments has none of
-- tier / reason_code / reason_text / week_number, scheduled_workouts has
-- neither rationale_short nor rationale_full, and the partial tier index is
-- absent. This is one of the "re-stamped entries" documented in
-- docs/migration-ledger-reconciliation-2026-06-11.md.
--
-- Because the ledger believes 20260424100000 ran, a normal `supabase db push`
-- will SKIP it — so these columns would never appear. Worse, the next pending
-- migration (20260703120000) runs `COMMENT ON COLUMN
-- plan_adjustments.reason_code`, which FAILS when the column is missing,
-- aborting the whole push.
--
-- This migration forward-fixes that. It is fully idempotent (ADD COLUMN IF NOT
-- EXISTS / CREATE INDEX IF NOT EXISTS), so it is correct whether or not the
-- ghost migration's effects happen to be present — the same "correct in either
-- world" pattern used by the sibling 20260703121000_plan_template_shape_columns.
--
-- ORDERING: timestamped 20260703115000 so `db push` applies it BEFORE
-- 20260703120000 (vocab CHECK + reason_code comment) and 20260703121000. It
-- adds no CHECK vocabulary of its own; 20260703120000 remains the source of
-- truth for the trigger_type / action_type value sets.
--
-- It faithfully reproduces the column/index body of 20260424100000. It does NOT
-- touch RLS (no new tables; existing plan_adjustments / scheduled_workouts
-- policies from 20260313100000_lock_down_rls.sql continue to apply).
-- ============================================================================

BEGIN;

-- plan_adjustments: three-tier customization model columns.
ALTER TABLE plan_adjustments
    ADD COLUMN IF NOT EXISTS tier TEXT
        CHECK (tier IS NULL OR tier IN ('green', 'yellow', 'red')),
    ADD COLUMN IF NOT EXISTS reason_code TEXT,
    ADD COLUMN IF NOT EXISTS reason_text TEXT,
    ADD COLUMN IF NOT EXISTS week_number INTEGER;

COMMENT ON COLUMN plan_adjustments.tier IS
    'Athlete-action severity: green (routine), yellow (flagged to coach), '
    'red (blocked). Null = legacy row from before this column existed.';

COMMENT ON COLUMN plan_adjustments.reason_text IS
    'Free-text when the actor adds detail. Coach rewrites and athlete moves '
    'both write here.';

COMMENT ON COLUMN plan_adjustments.week_number IS
    'Which plan-week this adjustment affects. Scopes weekly reshapes and the '
    'coach''s "plan changes" feed.';

-- reason_code comment intentionally omitted here — 20260703120000 owns the
-- authoritative reason_code comment (the closed move-day + coach-rewrite
-- vocabularies) and now runs cleanly because this migration created the column.

-- scheduled_workouts: per-day coach rationale (Phase C consumer;
-- generate-day-rationale backfills these). Reproduced from the ghost migration
-- so prod matches what the ledger claims.
ALTER TABLE scheduled_workouts
    ADD COLUMN IF NOT EXISTS rationale_short TEXT,
    ADD COLUMN IF NOT EXISTS rationale_full JSONB;

COMMENT ON COLUMN scheduled_workouts.rationale_short IS
    'One-line coach rationale shown as subtitle on the athlete''s week view. '
    'Generated by generate-day-rationale. Null = not yet backfilled.';

COMMENT ON COLUMN scheduled_workouts.rationale_full IS
    'Structured rationale: { why_today, why_this_workout, why_this_pace }. '
    'Surfaced in the "Why?" drawer. Null = not yet backfilled.';

-- Partial index backing the coach's "recent flagged adjustments" query.
CREATE INDEX IF NOT EXISTS idx_plan_adjustments_tier_applied
    ON plan_adjustments(user_id, applied_at DESC)
    WHERE tier IS NOT NULL AND tier <> 'green';

COMMIT;
